{
 "title": "Kafka Broker Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages per topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_typeName",
     "groupBy": [
      { "params": [ "typeName" ], "type": "tag" }
     ],
     "measurement": "MessagesInPerSecPerTopic",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Critical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UnderReplicatedPartitions",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Partition / Leader Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PartitionCount",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LeaderCount",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OfflinePartitionsCount",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "mmConsumerFetchMetrics",
     "query": "SELECT \"Value\" FROM \"ConsumerLag\" WHERE (\"typeName\" != 'type=FetcherLagMetrics,name=ConsumerLag,clientId=ReplicaFetcherThread-0-10,topic=__consumer_offsets,partition=1' OR \"typeName\" != 'type=FetcherLagMetrics,name=ConsumerLag,clientId=ReplicaFetcherThread-0-10,topic=__consumer_offsets,partition=10' OR \"typeName\" != 'type=FetcherLagMetrics,name=ConsumerLag,clientId=ReplicaFetcherThread-0-10,topic=__consumer_offsets,partition=11') AND $timeFilter GROUP BY \"typeName\"",
     "select": [
      [
       { "params": [ "records-lag-max" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Bytes In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesInPerSec",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesInPerSecPerTopic",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t1" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesInPerSec,topic=t1"
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesInPerSecPerTopic",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t2" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesInPerSec,topic=t2"
      }
     ]
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesOutPerSec",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesOutPerSecPerTopic",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t1" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesOutPerSec,topic=t1"
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesOutPerSecPerTopic",
     "select": [
      [
       { "params": [ "Count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t2" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesOutPerSec,topic=t2"
      }
     ]
    }
   ]
  },
  {
   "title": "Bytes In (5 minute rate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesInPerSec",
     "select": [
      [
       { "params": [ "FiveMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesInPerSecPerTopic",
     "select": [
      [
       { "params": [ "FiveMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t1" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesInPerSec,topic=t1"
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesInPerSecPerTopic",
     "select": [
      [
       { "params": [ "FiveMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t2" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesInPerSec,topic=t2"
      }
     ]
    }
   ]
  },
  {
   "title": "Bytes Out (5 minute rate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesOutPerSec",
     "select": [
      [
       { "params": [ "FiveMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesOutPerSecPerTopic",
     "select": [
      [
       { "params": [ "FiveMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t1" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesOutPerSec,topic=t1"
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "BytesOutPerSecPerTopic",
     "select": [
      [
       { "params": [ "FiveMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "topic_t2" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "typeName",
       "operator": "=",
       "value": "type=BrokerTopicMetrics,name=BytesOutPerSec,topic=t2"
      }
     ]
    }
   ]
  },
  {
   "title": "Request Handler avg idle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RequestHandlerAvgIdlePercent",
     "select": [
      [
       { "params": [ "MeanRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests Total Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ProduceTotalTimeMs",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FetchConsumerTotalTimeMs",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FetchFollowerTotalTimeMs",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Queue Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ProduceRequestQueueTimeMs",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FetchConsumerRequestQueueTimeMs",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FetchFollowerRequestQueueTimeMs",
     "select": [
      [
       { "params": [ "Mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Kafka Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Leader Election",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "LeaderElectionRateAndTimeMs",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UncleanLeaderElectionsPerSec",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "ActiveControllerCount",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Log Flush latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LogFlush",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Messages In per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MessagesInPerSec",
     "select": [
      [
       { "params": [ "OneMinuteRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "OS Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Memory (JVM & Physical)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvmMemory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage_init" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "heap" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "attributeName", "operator": "=", "value": "HeapMemoryUsage" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jvmMemory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage_init" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "non-heap" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "attributeName", "operator": "=", "value": "NonHeapMemoryUsage" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "os",
     "select": [
      [
       { "params": [ "FreePhysicalMemorySize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "physical" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}