{
 "title": "Kafka Consumer Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "App",
    "query": "label_values(kafka_consumer_kafka_metrics_count_count, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Max lag for any partition",
   "type": "graph",
   "description": "The maximum lag in terms of number of records for any partition in this window. An increasing value over time is your best indication that the consumer group is not keeping up with the producers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "# records" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_fetch_manager_metrics_records_lag{name=~\"$App\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Assigned Partitions",
   "type": "graph",
   "description": "The number of partitions currently assigned to this consumer",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(kafka_consumer_consumer_coordinator_metrics_assigned_partitions{name=~\"$App\"}) by (kubernetes_pod_name) ",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Bytes Consumed per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_rate{name=~\"$App\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Fetch Latency (avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg{name=~\"$App\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Fetch Requests per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumer_consumer_fetch_manager_metrics_fetch_rate{name=~\"$App\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Records per request",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "rec/req" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_fetch_manager_metrics_records_per_request_avg{topic!=\"\", name=~\"$App\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Records per second",
   "type": "graph",
   "description": "The average number of records per second",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "rec/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{topic!=\"\", name=~\"$App\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Commit Latency (avg)",
   "type": "graph",
   "description": "The average time taken for a commit request.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_coordinator_metrics_commit_latency_avg{name=~\"$App\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Commits per second",
   "type": "graph",
   "description": "The number of commit calls per second.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "commit/s" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_coordinator_metrics_commit_rate{name=~\"$App\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "IO Time (avg)",
   "type": "graph",
   "description": "The average length of time for I/O per select call in nanoseconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_metrics_io_time_ns_avg{name=~\"$App\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "IO Time (avg)",
   "type": "graph",
   "description": "The average length of time for I/O per select call in nanoseconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_metrics_io_time_ns_avg{name=~\"$App\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "IO Ratio (avg)",
   "type": "graph",
   "description": "The fraction of time the I/O thread spent doing I/O.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_metrics_io_ratio{name=~\"$App\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "IO Wait Ratio (avg)",
   "type": "graph",
   "description": "The fraction of time the I/O thread spent waiting.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_metrics_io_wait_ratio{name=~\"$App\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Heartbeat Rate",
   "type": "graph",
   "description": "The average number of heartbeats per second. After a rebalance, the consumer sends heartbeats to the coordinator to keep itself active in the group. You can control this using the heartbeat.interval.ms setting for the consumer. You may see a lower rate than configured if the processing loop is taking more time to handle message batches. Usually this is OK as long as you see no increase in the join rate.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "heartbeats/s" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_coordinator_metrics_heartbeat_rate{name=~\"$App\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Sync Rate",
   "type": "graph",
   "description": "The number of group syncs per second. Group synchronization is the second and last phase of the rebalance protocol. Similar to join-rate, a large value indicates group instability.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "syncs/s" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_coordinator_metrics_sync_rate{name=~\"$App\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Join Rate",
   "type": "graph",
   "description": "The number of group joins per second. Group joining is the first phase of the rebalance protocol. A large value indicates that the consumer group is unstable and will likely be coupled with increased lag.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "joins/s" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_consumer_consumer_coordinator_metrics_join_rate{name=~\"$App\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}